<a href="https://colab.research.google.com/github/factorLee/FastCampus/blob/main/Adaboost.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Adaboost

In [ ]:
import os
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [ ]:
# 현재경로 확인
os.getcwd()

'/content'

In [ ]:
# 데이터 불러오기
data = pd.read_csv("./otto_train.csv") # Product Category
data.head() # 데이터 확인

   id  feat_1  feat_2  feat_3  ...  feat_91  feat_92  feat_93   target
0   1       1       0       0  ...        0        0        0  Class_1
1   2       0       0       0  ...        0        0        0  Class_1
2   3       0       0       0  ...        0        0        0  Class_1
3   4       1       0       0  ...        0        0        0  Class_1
4   5       0       0       0  ...        0        0        0  Class_1

[5 rows x 95 columns]

In [ ]:
'''
id: 고유 아이디
feat_1 ~ feat_93: 설명변수
target: 타겟변수 (1~9)
'''

'\nid: 고유 아이디\nfeat_1 ~ feat_93: 설명변수\ntarget: 타겟변수 (1~9)\n'

In [ ]:
nCar = data.shape[0] # 데이터 개수
nVar = data.shape[1] # 변수 개수
print('nCar: %d' % nCar, 'nVar: %d' % nVar )

nCar: 61878 nVar: 95

## 의미가 없다고 판단되는 변수 제거

In [ ]:
data = data.drop(['id'], axis = 1) # id 제거

## 타겟 변수의 문자열을 숫자로 변환

In [ ]:
data.head() # 데이터 확인

   feat_1  feat_2  feat_3  feat_4  ...  feat_91  feat_92  feat_93   target
0       1       0       0       0  ...        0        0        0  Class_1
1       0       0       0       0  ...        0        0        0  Class_1
2       0       0       0       0  ...        0        0        0  Class_1
3       1       0       0       1  ...        0        0        0  Class_1
4       0       0       0       0  ...        0        0        0  Class_1

[5 rows x 94 columns]

In [ ]:
mapping_dict = {"Class_1": 1,
                "Class_2": 2,
                "Class_3": 3,
                "Class_4": 4,
                "Class_5": 5,
                "Class_6": 6,
                "Class_7": 7,
                "Class_8": 8,
                "Class_9": 9
                }

In [ ]:
after_mapping_target = data['target'].apply(lambda x: mapping_dict[x])
#after_mapping_target = data['target'].apply(lambda x: mapping_dict[x])

## 설명변수와 타겟변수를 분리, 학습데이터와 평가데이터 분리

In [ ]:
feature_columns = list(data.columns.difference(['target'])) # target을 제외한 모든 행
X = data[feature_columns] # 설명변수
y = after_mapping_target # 타겟변수
train_x, test_x, train_y, test_y = train_test_split(X, y, test_size = 0.2, random_state = 42) # 학습데이터와 평가데이터의 비율을 8:2 로 분할| 
print(train_x.shape, test_x.shape, train_y.shape, test_y.shape) # 데이터 개수 확인

(49502, 93) (12376, 93) (49502,) (12376,)

## 학습 데이터를 에이다부스트 모형에 적합 후 평가 데이터로 검증

In [ ]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
tree_model = DecisionTreeClassifier(max_depth=5)

clf = AdaBoostClassifier(base_estimator = tree_model, n_estimators=10, random_state=0)
clf.fit(train_x, train_y) 
pred1=clf.predict(test_x)
print(accuracy_score(test_y, pred1))

0.6853587588881707

## 추정을 많이 해보는건 어떨까?

In [ ]:
tree_model = DecisionTreeClassifier(max_depth=5)

clf = AdaBoostClassifier(base_estimator = tree_model, n_estimators=100, random_state=0)
clf.fit(train_x, train_y) 
pred1=clf.predict(test_x)
print(accuracy_score(test_y, pred1))

0.6061732385261797

## 트리의 깊이를 늘려보는건 어떨까?

In [ ]:
tree_model = DecisionTreeClassifier(max_depth=20)

clf = AdaBoostClassifier(base_estimator = tree_model, n_estimators=10, random_state=0)
clf.fit(train_x, train_y) 
pred1=clf.predict(test_x)
print(accuracy_score(test_y, pred1))

0.7133968972204267

## 트리의 깊이를 최대로 늘려보자!

In [ ]:
tree_model = DecisionTreeClassifier(max_depth=100)

clf = AdaBoostClassifier(base_estimator = tree_model, n_estimators=10, random_state=0)
clf.fit(train_x, train_y) 
pred1=clf.predict(test_x)
print(accuracy_score(test_y, pred1))

0.7099224305106658

## 다른 하이퍼파라미터에 대한 정보를 얻고싶으면 링크를 참조
- https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.AdaBoostClassifier.html